###########################################################################
# PRODUCTION
###########################################################################
# build_push2:
#     stage: build
#     only:
#         - master
#     tags:
#         - nwpush2
#     script:
#         - yarn
#         - yarn build

# deploy_push2:
#     stage: deploy
#     only:
#         - master
#     tags:
#         - nwpush2
#     script:
#         - cd ~/builds
#         - scp -rp Deploy/* apuser@172.17.6.6:/ap/nweb/NewWeb
#         - scp -rp Deploy/* apuser@172.17.2.6:/ap/nweb/NewWeb

###########################################################################
# UAT
###########################################################################
build_newwebrd:
    stage: build
    only:
        - UAT
    tags:
        - nwwebrd
    script:
        - cd $CI_PROJECT_DIR
        - yarn
        - yarn build
        - mkdir -p ~/build
        - cp -fRv $CI_PROJECT_DIR ~/build

deploy_newwebrd:
    stage: deploy
    only:
        - UAT
    tags:
        - nwwebrd
    script:
        - pm2 stop new-newweb
        - cd ~/build/$CI_PROJECT_NAME
        - yarn pm2
