stages:
    - build
    - stop
    - deploy

###########################################################################
# PRODUCTION
###########################################################################
# build_push2:
#     stage: build
#     only:
#         - master
#     tags:
#         - nwpush2
#     script:
#         - yarn
#         - yarn build

# deploy_push2:
#     stage: deploy
#     only:
#         - master
#     tags:
#         - nwpush2
#     script:
#         - cd ~/builds
#         - scp -rp Deploy/* apuser@172.17.6.6:/ap/nweb/NewWeb
#         - scp -rp Deploy/* apuser@172.17.2.6:/ap/nweb/NewWeb

###########################################################################
# UAT
###########################################################################
build_newwebrd:
    stage: build
    tags:
        - nwwebrd
    only:
        - UAT
    script:
        - rm -rf ~/new_newweb
        - mkdir -p ~/new_newweb
        - cp -fRv $CI_PROJECT_DIR/*. ~/new_newweb
        - cd ~/new_newweb
        - yarn
        - yarn build

stop_newwebrd:
    stage: stop
    allow_failure: true
    tags:
        - nwwebrd
    only:
        - UAT
    script:
        - pm2 stop new-newweb

deploy_newwebrd:
    stage: deploy
    tags:
        - nwwebrd
    only:
        - UAT
    script:
        - cd ~/new_newweb
        - NODE_ENV=production pm2 start server.js --node-args="--max-http-header-size=16000" -n new-newweb
