stages:
    - build
    - stop
    - deploy

###########################################################################
# PRODUCTION
###########################################################################
build_push2:
    stage: build
    tags:
        - nwpush2
    only:
        - master
    script:
        - cd $CI_PROJECT_DIR
        - yarn
        - yarn build
        - ssh apuser@172.17.2.6 'mkdir -p ~/new_newweb'
        - ssh apuser@172.17.6.6 'mkdir -p ~/new_newweb'
        - scp -rp $CI_PROJECT_DIR/. apuser@172.17.2.6:/ap/nweb/new_newweb
        - scp -rp $CI_PROJECT_DIR/. apuser@172.17.6.6:/ap/nweb/new_newweb

stop_push2:
    stage: stop
    allow_failure: true
    tags:
        - nwpush2
    only:
        - master
    script:
        - ssh apuser@172.17.2.6 'pm2 stop new-newweb'
        - ssh apuser@172.17.6.6 'pm2 stop new-newweb'

deploy_push2:
    stage: deploy
    tags:
        - nwpush2
    only:
        - master
    script:
        - ssh apuser@172.17.2.6 'cd ~/new_newweb; NODE_ENV=production pm2 start server.js --node-args="--max-http-header-size=16000" -n new-newweb'
        - ssh apuser@172.17.6.6 'cd ~/new_newweb; NODE_ENV=production pm2 start server.js --node-args="--max-http-header-size=16000" -n new-newweb'

###########################################################################
# UAT
###########################################################################
build_newwebrd:
    stage: build
    tags:
        - nwwebrd
    only:
        - UAT
    script:
        - cd $CI_PROJECT_DIR
        - yarn
        - yarn build
        - mkdir -p ~/new_newweb
        - cp -fRv $CI_PROJECT_DIR/. ~/new_newweb

stop_newwebrd:
    stage: stop
    allow_failure: true
    tags:
        - nwwebrd
    only:
        - UAT
    script:
        - pm2 stop new-newweb

deploy_newwebrd:
    stage: deploy
    tags:
        - nwwebrd
    only:
        - UAT
    script:
        - cd ~/new_newweb
        - NODE_ENV=production pm2 start server.js --node-args="--max-http-header-size=16000" -n new-newweb
