stages:
    - build
    - deploy

###########################################################################
# PRODUCTION
###########################################################################
build_nwweb1:
    stage: build
    tags:
        - nwweb1
    only:
        - master
    script:
        - cd $CI_PROJECT_DIR
        - yarn
        - yarn build
        - mkdir -p ~/new_newweb
        - cp -fRv $CI_PROJECT_DIR/. ~/new_newweb
        - cd ~/new_newweb
        - mv .env.production.example .env

deploy_nwweb1:
    stage: deploy
    tags:
        - nwweb1
    only:
        - master
    script:
        - pm2 stop -s new-newweb
        - cd ~/new_newweb
        - NODE_ENV=production pm2 start server.js --node-args="--max-http-header-size=16000" -n new-newweb

build_nwweb2:
    stage: build
    tags:
        - nwweb2
    only:
        - master
    script:
        - cd $CI_PROJECT_DIR
        - yarn
        - yarn build
        - mkdir -p ~/new_newweb
        - cp -fRv $CI_PROJECT_DIR/. ~/new_newweb
        - cd ~/new_newweb
        - mv .env.production.example .env

deploy_nwweb2:
    stage: deploy
    tags:
        - nwweb2
    only:
        - master
    script:
        - pm2 stop -s new-newweb
        - cd ~/new_newweb
        - NODE_ENV=production pm2 start server.js --node-args="--max-http-header-size=16000" -n new-newweb

###########################################################################
# UAT
###########################################################################
build_nwwebrd:
    stage: build
    tags:
        - nwwebrd
    only:
        - UAT
    script:
        - cd $CI_PROJECT_DIR
        - yarn
        - yarn build
        - mkdir -p ~/new_newweb
        - cp -fRv $CI_PROJECT_DIR/. ~/new_newweb
        - cd ~/new_newweb
        - mv .env.development.example .env

deploy_nwwebrd:
    stage: deploy
    tags:
        - nwwebrd
    only:
        - UAT
    script:
        - pm2 stop -s new-newweb
        - cd ~/new_newweb
        - NODE_ENV=production pm2 start server.js --node-args="--max-http-header-size=16000" -n new-newweb
