stages:
    - build
    - deploy

###########################################################################
# PRODUCTION
###########################################################################
build_push2:
    stage: build
    tags:
        - nwpush2
    only:
        - master
    script:
        - cd $CI_PROJECT_DIR
        - mv .env.production.example .env
        - yarn
        - yarn build
        - ssh apuser@172.17.2.6 'mkdir -p ~/new_newweb'
        - ssh apuser@172.17.6.6 'mkdir -p ~/new_newweb'
        - rsync -avz -e ssh --progress $CI_PROJECT_DIR/. apuser@172.17.2.6:~/new_newweb --exclude .git
        - rsync -avz -e ssh --progress $CI_PROJECT_DIR/. apuser@172.17.6.6:~/new_newweb --exclude .git

deploy_push2:
    stage: deploy
    tags:
        - nwpush2
    only:
        - master
    script:
        - ssh apuser@172.17.2.6 'pm2 restart new-newweb'
        - ssh apuser@172.17.6.6 'pm2 restart new-newweb'
        # - ssh apuser@172.17.2.6 'cd ~/new_newweb; NODE_ENV=production pm2 start server.js --node-args="--max-http-header-size=16000" -n new-newweb'
        # - ssh apuser@172.17.6.6 'cd ~/new_newweb; NODE_ENV=production pm2 start server.js --node-args="--max-http-header-size=16000" -n new-newweb'

###########################################################################
# UAT
###########################################################################
build_nwwebrd:
    stage: build
    tags:
        - nwwebrd
    only:
        - UAT
    script:
        - cd $CI_PROJECT_DIR
        - mv .env.development.example .env
        - yarn
        - yarn build
        - mkdir -p ~/new_newweb
        - cp -fRv $CI_PROJECT_DIR/. ~/new_newweb
        - cd ~/new_newweb

deploy_nwwebrd:
    stage: deploy
    tags:
        - nwwebrd
    only:
        - UAT
    script:
        - pm2 stop -s new-newweb
        - cd ~/new_newweb
        - NODE_ENV=production pm2 start server.js --node-args="--max-http-header-size=16000" -n new-newweb
