var _taLabels = {
    MACD: 'MACD',
    Signal: '訊號',
    Histogram: 'OSCI',
    ADXR: '',
    UB: '上行通道',
    LB: '下行通道',
    SAR_Param1: '始值',
    SAR_Param2: '加速因數',
    SAR_Param3: '上限',
    BB_ParamMid: '移動平均',
    SMA: 'SMA',
    EMA: 'EMA',
    MEMA: 'MEMA',
    WMA: 'WMA',
    close: '收盤價',
    Close: '收盤價',
    turnover: '成交金額',
    Volume: '成交量',
};
var _taNamesShort = {
    Volume: '成交量',
    Turnover: '成交金額',
    SMA: 'SMA',
    EMA: 'EMA',
    MEMA: 'MEMA',
    WMA: 'WMA',
    RSI: 'RSI',
    MACD: 'MACD',
    BB: 'BB',
    SAR: 'SAR',
    FKD: 'Fast STC',
    SKD: 'Slow STC',
    FFKD: 'Full STC',
    LINE: '一個月 外匯調查',
    DMI: 'DMI',
    OBV: 'OBV',
    WR: 'WR',
    VAP: 'VAP',
    ICH: 'Ichimoku',
    MOM: 'Momentum',
    PreviousClose: '前收市',
};
var _taNames = {
    Volume: '成交量',
    Turnover: '成交金額',
    SMA: '移動平均線',
    EMA: '指數移動平均線',
    MEMA: '修正指數移動平均線',
    WMA: '加權移動平均線',
    RSI: '相對強弱指數',
    MACD: '移動平均匯聚背馳指標',
    BB: '保力加通道',
    SAR: '拋物轉向',
    FKD: '隨機快步指數',
    SKD: '隨機慢步指數',
    FFKD: '隨機指數',
    LINE: '一個月 外匯調查',
    DMI: '動向指數',
    OBV: '淨值成交量',
    WR: '威廉指數',
    VAP: '價位區間成交量',
    ICH: '一目均衡',
    MOM: '動力指數',
    PreviousClose: '前收市價',
};
