var _taLabels = {
"MACD":"MACD",
"Signal":"讯号",
"Histogram":"OSCI",
"ADXR":"",
"UB":"上行通道",
"LB":"下行通道",
"SAR_Param1":"始值",
"SAR_Param2":"加速因数",
"SAR_Param3":"上限",
"BB_ParamMid":"移动平均",
"SMA":"SMA",
"EMA":"EMA",
"MEMA":"MEMA",
"WMA":"WMA", 
"close":"收盘价",
"Close":"收盘价",
"turnover" :"成交金额",
"Volume":"成交量"
};
var _taNamesShort = {
"Volume":"成交量",
"Turnover":"成交金额",
"SMA":"SMA",
"EMA":"EMA",
"MEMA":"MEMA",
"WMA":"WMA",
"RSI":"RSI",
"MACD":"MACD",
"BB":"BB",
"SAR":"SAR",
"FKD":"Fast STC",
"SKD":"Slow STC",
"FFKD":"Full STC",
"LINE":"一个月 外汇调查",
"DMI":"DMI",
"OBV":"OBV",
"WR":"WR",
"VAP":"VAP",
"ICH":"Ichimoku",
"MOM": "Momentum",
"PreviousClose":"前收市"
};
var _taNames = {
"Volume":"成交量",
"Turnover":"成交金额",
"SMA":"移动平均线",
"EMA":"指数移动平均线",
"MEMA":"修正指数移动平均线",
"WMA":"加权移动平均线",
"RSI":"相对强弱指数",
"MACD":"移动平均汇聚背驰指标",
"BB":"保力加通道",
"SAR":"抛物转向",
"FKD":"随机快步指数",
"SKD":"随机慢步指数",
"FFKD":"随机指数",
"LINE":"一个月 外汇调查",
"DMI":"动向指数",
"OBV":"净值成交量",
"WR":"威廉指数",
"VAP":"价位区间成交量",
"ICH":"一目均衡",
"MOM": "动力指数",
"PreviousClose":"前收市价"
};