var _taLabels = {
"MACD":"MACD",
"Signal":"Signal",
"Histogram":"OSCI",
"ADXR":"",
"UB":"Upper Band",
"LB":"Lower Band",
"SAR_Param1":"Prior",
"SAR_Param2":"AF",
"SAR_Param3":"EP",
"BB_ParamMid":"Moving Average",
"SMA":"SMA",
"EMA":"EMA",
"MEMA":"MEMA",
"WMA":"WMA", 
"close":"Close",
"Close":"Close",
"turnover" :"Turnover",
"Volume":"Volume"
};
var _taNamesShort = {
"Volume":"Volume",
"Turnover":"Turnover",
"SMA":"Simple Moving Average",
"EMA":"EMA",
"MEMA":"MEMA",
"WMA":"WMA",
"RSI":"RSI",
"MACD":"MACD",
"BB":"BB",
"SAR":"SAR",
"FKD":"Fast STC",
"SKD":"Slow STC",
"FFKD":"Full STC",
"LINE":"1 Month FX Poll",
"DMI":"DMI",
"OBV":"OBV",
"WR":"WR",
"VAP":"VAP",
"ICH":"Ichimoku",
"MOM": "Momentum",
"PreviousClose":"Prev.Cls"
};
var _taNames = {
"Volume":"Volume",
"Turnover":"Turnover",
"SMA":"Simple Moving Average",
"EMA":"EMA",
"MEMA":"MEMA",
"WMA":"WMA",
"RSI":"Relative Strength Index",
"MACD":"Moving Average Convergence Divergence",
"BB":"Bollinger Bands",
"SAR":"SAR",
"FKD":"Fast STC",
"SKD":"Slow STC",
"FFKD":"Full Stochastic",
"LINE":"1 Month FX Poll",
"DMI":"Directional Movement Indicator",
"OBV":"OBV",
"WR":"WR",
"VAP":"VAP",
"ICH":"Ichimoku",
"MOM": "Momentum",
"PreviousClose":"Previous Close"
};