// Resource - en
LabCI.WP.PSPageObj.PAGEOBJ_RESOURCEBUNDLE.en = {
    placeholder: 'Search stock by code or name',
    empty: 'No result found',
    NXB: 'USA NASDAQ',
    NBA: 'USA AMEX',
    NBN: 'USA NYSE',
    NYQ: 'USA NYSE',
    ASQ: 'USA AMEX',
    NMQ: 'USA NASDAQ',
    NAQ: 'USA NASDAQ',
    PCQ: 'USA NYSE',
    NSQ: 'USA NASDAQ',
    OTC: 'USA PINK',
    PNK: 'USA PINK',
    OBB: 'USA OTC',
    HKG: 'HK HKEX',
    TAI: 'Taiwan TWSE',
    TWO: 'Taiwan TPEX',
    SHH: 'China SSE',
    SHZ: 'China SZSE',
};
