// Resource - zh_CN
LabCI.WP.PSPageObj.PAGEOBJ_RESOURCEBUNDLE.zh_CN = {
    placeholder: '按代码或名称搜索股票',
    empty: '没有搜寻结果',
    NXB: '美国 NASDAQ',
    NBA: '美国 AMEX',
    NBN: '美国 NYSE',
    NYQ: '美国 NYSE',
    ASQ: '美国 AMEX',
    NMQ: '美国 NASDAQ',
    NAQ: '美国 NASDAQ',
    PCQ: '美国 NYSE',
    NSQ: '美国 NASDAQ',
    OTC: '美国 PINK',
    PNK: '美国 PINK',
    OBB: '美国 OTC',
    HKG: '香港 HKEX',
    TAI: '台湾 TWSE',
    TWO: '台湾 TPEX',
    SHH: '中国 SSE',
    SHZ: '中国 SZSE',
};
