
// Resource - zh_TW
LabCI.WP.QuotePageObj.PAGEOBJ_RESOURCEBUNDLE.zh_HK = {

    lbl: {
        "buybutton2": "我要下單",
        "buybutton": "買入",
        "sellbutton": "賣出",
        "summarylabel": "概要",
        "chartlabel": "圖表",
        "financiallabel": "財務資料",
        "stockreportlabel": "股票報告",
        "watchlistbutton": "加入自選",
        "NXB": "美國 NASDAQ",
        "NBA": "美國 AMEX",
        "NBN": "美國 NYSE",       
        "NYQ": "美國 NYSE",
        "ASQ": "美國 AMEX",
        "NMQ": "美國 NASDAQ",
        "NAQ": "美國 NASDAQ",
        "PCQ": "美國 NYSE",
        "NSQ": "美國 NASDAQ",
        "OTC": "美國 PINK",
        "PNK": "美國 PINK",
        "OBB": "美國 OTC",
        "HKG": "香港 HKEX",
        "TAI": "台灣 TWSE",  
        "TWO": "台灣 TPEX", 
        "SHH": "中國 SSE",
        "SHZ": "中國 SZSE",
        "delay": "延遲報價",
        "real": "實時報價",
        "realStream": "實時報價",
        "ccy": " ",
        "ccy_CNY": "人民幣",
        "ccy_EUR": "歐元",
        "ccy_HKD": "港元",
        "ccy_TWD": "新臺幣",        
        "ccy_NOK": "挪威克朗",
        "ccy_USD": "美元",
        "lblopen": "開市價",
        "lblhigh": "最高價",
        "lbllow": "最低價",
        "lblvwap": "成交量加權平均價",
        "lblwk52high": "52週最高價",
        "lblwk52low": "52週最低價",
        "lblmarketcap": "巿值",
        "lblbid": "買入價",
        "lblask": "賣出價",
        "lblpc": "前收市價",
        "lbleps": "每股盈餘 (TTM)",
        "lblper": "本益比 (TTM)",
        "lblpbr": "股價淨值比 (LFY)",
        "lbllotsize": "每手股數",
        "lbldividend": "股利",
        "lbldividendyield": "股票殖利率",
        "lbldividendexdate": "除息日",
        "lbldividendpaydate": "股利發放日",
        "lblvolume": "成交量",
        "lblturnover": "成交金額",
        "lblcode": "股票編號",
        "lblcompany": "股票名稱",
        "lblsector": "板塊",
        "lbllast": "現價",
        "lblchange": "漲跌價",
        "lblchangepct": "漲跌幅",
        "lblturnoverMil": "成交金額",
        "lblinvalidRicBody": "不正確代碼或名稱. 請再次輸入",
        "lblclose": "關閉",
        "lblstockof": " 項目 ",
        "lblstocktotal": " 股票", 
        "lblprev": "前",
        "lblnext": "後" ,
        "lblpeer": "同業個股",
        "lblnoresults": "沒有結果"        
    }

};