
// Resource - zh_TW
LabCI.WP.QuotePageObj.PAGEOBJ_RESOURCEBUNDLE.en = {

    lbl: {
        "buybutton2": "PLACE ORDER",
        "buybutton": "BUY",
        "sellbutton": "SELL",
        "summarylabel": "Summary",
        "chartlabel": "Chart",
        "financiallabel": "Financial",
        "stockreportlabel": "Stock Report+",
        "watchlistbutton": "Add Favourites",
        "NXB": "USA NASDAQ",
        "NBA": "USA AMEX",
        "NBN": "USA NYSE",        
        "NYQ": "USA NYSE",
        "ASQ": "USA AMEX",
        "NMQ": "USA NASDAQ",
        "NAQ": "USA NASDAQ",
        "PCQ": "USA NYSE",
        "NSQ": "USA NASDAQ",
        "OTC": "USA PINK",
        "PNK": "USA PINK",
        "OBB": "USA OTC",
        "HKG": "HK HKEX",
        "TAI": "Taiwan TWSE",   
        "TWO": "Taiwan TPEX", 
        "SHH": "China SSE",
        "SHZ": "China SZSE",
        "delay": "Delayed. ",
        "real": "Realtime. ",
        "realStream": "Realtime. ",
        "ccy": "Currency in ",
        "ccy_CNY": "CNY",
        "ccy_EUR": "EUR",
        "ccy_HKD": "HKD",
        "ccy_TWD": "TWD",
        "ccy_NOK": "NOK",
        "ccy_USD": "USD",
        "lblopen": "Open",
        "lblhigh": "High",
        "lbllow": "Low",
        "lblvwap": "VWAP",
        "lblwk52high": "52W High",
        "lblwk52low": "52W Low",
        "lblmarketcap": "Market Cap",
        "lblbid": "Bid",
        "lblask": "Ask",
        "lblpc": "Previous Close",
        "lbleps": "EPS (TTM)",
        "lblper": "PER (TTM)",
        "lblpbr": "PBR (LFY)",
        "lbllotsize": "Lot Size",
        "lbldividend": "Dividend",
        "lbldividendyield": "Dividend Yield",
        "lbldividendexdate": "Dividend Ex Date",
        "lbldividendpaydate": "Dividend Pay Date",
        "lblvolume": "Volume",
        "lblturnover": "Turnover",
        "lblcode": "Code",
        "lblcompany": "Company",
        "lblsector": "Sector",
        "lbllast": "Last",
        "lblchange": "Change",
        "lblchangepct": "Change %",
        "lblturnoverMil": "Turnover",
        "lblinvalidRicBody": "Invalid stock code or name. Please try again",
        "lblclose": "Close",
        "lblstockof": " of ",
        "lblstocktotal": " stock(s)",  
        "lblprev": "Previous",
        "lblnext": "Next",
        "lblpeer": "Peer Stocks",
        "lblnoresults": "No Results"
    }

};