
// Resource - zh_TW
LabCI.WP.QuotePageObj.PAGEOBJ_RESOURCEBUNDLE.zh_CN = {

    lbl: {
        "buybutton2": "我要下单",
        "buybutton": "买进",
                "sellbutton": "卖出",
                "summarylabel": "概要",
                "chartlabel": "图表",
                "financiallabel": "财务资料",
                "stockreportlabel": "股票报告",
                "watchlistbutton": "加入自选",
    "NXB": "美国 NASDAQ",
    "NBA": "美国 AMEX",
    "NBN": "美国 NYSE",        
                "NYQ": "美国 NYSE",
                "ASQ": "美国 AMEX",
                "NMQ": "美国 NASDAQ",
                "NAQ": "美国 NASDAQ",
                "PCQ": "美国 NYSE",
                "NSQ": "美国 NASDAQ",
                "OTC": "美国 PINK",
                "PNK": "美国 PINK",
                "OBB": "美国 OTC",
                "HKG": "香港 HKEX",
        "TAI": "台湾 TWSE",
        "TWO": "台湾 TPEX",
                "SHH": "中国 SSE",
                "SHZ": "中国 SZSE",
                "delay": "延迟报价",
                "real": "实时报价",
                "ccy": " ",
                "ccy_CNY": "人民币",
                "ccy_EUR": "欧元",
                "ccy_HKD": "港元",
        "ccy_TWD": "新台币",
                "ccy_NOK": "挪威克朗",
                "ccy_USD": "美元",
                "lblopen": "开盘价",
                "lblhigh": "最高价",
                "lbllow": "最低价",
                "lblvwap": "成交量加权平均价",
                "lblwk52high": "52周最高价",
                "lblwk52low": "52周最低价",
                "lblmarketcap": "巿值",
                "lblbid": "委买价",
                "lblask": "委卖价",
                "lblpc": "昨日收盘价",
                "lbleps": "每股盈余 (TTM)",
                "lblper": "本益比 (TTM)",
                "lblpbr": "股价净值比 (LFY)",
                "lbllotsize": "每手股数",
                "lbldividend": "股利",
                "lbldividendyield": "股票殖利率",
                "lbldividendexdate": "除息日",
                "lbldividendpaydate": "股利发放日",
                "lblvolume": "成交量",
                "lblturnover": "成交金额",
                "lblcode": "股票编号",
                "lblcompany": "股票名称",
                "lblsector": "板块",
                "lbllast": "现价",
                "lblchange": "涨跌价",
                "lblchangepct": "涨跌幅",
                "lblturnoverMil": "成交金额",
        "lblinvalidRicBody": "不正确代码或名称. 请再次输入",
        "lblclose": "关闭",
        "lblstockof": " 项目 ",
        "lblstocktotal": " 股票", 
        "lblprev": "前",
        "lblnext": "后",
        "lblpeer": "同业个股",
        "lblnoresults": "没有结果"         
    }

};