// Resource - zh_TW
LabCI.WP.RankingPageObj.PAGEOBJ_RESOURCEBUNDLE.en = {
    lbl: {
        refresh: 'Refresh',
        TWN: 'Taiwan TWSE',
        TWN_WNT: 'Taiwan Warrants',
        TWO: 'Taiwan TPEX',
        HKG: 'Hong Kong Market',
        HKG_MAIN: 'Hong Kong Mainboard',
        HKG_GEM: 'Hong Kong GEM Board',
        SHH: 'ShangHai A',
        SHZ: 'ShenZhen A',
        NYSE: 'NYSE',
        NYSE_AMER: 'NYSE American',
        NYSE_ARCA: 'NYSE ARCA',
        NASDAQ: 'NASDAQ',
        NG: 'Top Gainers',
        NL: 'Top Losers',
        PG: 'Top %Gainers',
        PL: 'Top %Losers',
        AV: 'Top Volume',
        AM: 'Top Turnover',
        cancel: 'Cancel',
        change: 'Change',
        volume: 'Volume',
        turnover: 'Turnover',
        'ranking-title': 'Top 20 %rank%<br/>%mkt%',
        add: 'Add',
        code: 'Code',
        name: 'Name',
        last: 'Last',
        changepct: 'Change %',
        buy: 'Order',
        sell: 'Sell',
        noresults: 'No Results',
        moreranks: 'More Ranks',
    },
};
