// Resource - zh_TW
LabCI.WP.ScreenerPageObj.PAGEOBJ_RESOURCEBUNDLE.zh_CN = {
    lbl: {
        5130: '应用资源',
        5310: '汽车零件',
        5510: '银行与投资服务',
        5110: '化学品',
        5320: '耐用消费品',
        5330: '消费者服务',
        5620: '药物与医学研究',
        5010: '能源',
        5410: '食品与饮料',
        5550: '基金',
        5610: '保健服务',
        5560: '控股公司',
        5230: '工业集团',
        5210: '工业品牌',
        5220: '工业服务',
        5530: '保险',
        5120: '矿产资源',
        5420: '个人及家庭用品及服务',
        5540: '房地产',
        5020: '再生能源',
        5340: '零售',
        5430: '零售 - 食品药物',
        5720: '软件及信息技术服务',
        5710: '技术设备',
        5810: '电信业务',
        5240: '运输',
        5030: '铀',
        5910: '公用事业',
        criteriatype_valuation: '估值',
        criteriatype_dividend: '股息',
        criteriatype_share_related: '股票相关项目',
        criteriatype_profitability_ratio: '盈利能力比率',
        criteriatype_pershare_ratio: '每股比率',
        criteriatype_mgt_effectiveness: '管理效能',
        criteriatype_financial_strength: '财务实力',
        criteriatype_efficiency_ratio: '成效比',
        criteriatype_growth_rate: '增长率',
        criteriatype_ta_trend: '技术指标(趋势)',
        criteriatype_ta_oscillator: '技术性指标(震荡)',
        criteriatype_price_volume: '价格和成交量',
        criteria_APENORM: '市盈率规范化',
        criteria_F_PBR: '市帐率',
        criteria_APRCFPS: '股价自由现金流比',
        criteria_APRICE2TOTEQ: '价格公平',
        criteria_F_PSR: '售价',
        criteria_F_DIV_YIELD: '股息收益率',
        criteria_F_DIV: '每股股息',
        criteria_F_MKTCAP_USD: '市值 (x百万定价货币)',
        criteria_FLOATPRC_CUR: '浮动占已发行股份总数的百分比',
        criteria_SHSBOUTAVG: '基本股, 平均(x百万)',
        criteria_SHSOUT: '流通股票, 现时(x百万)',
        criteria_SHSOUTAVG: '流通股票, 平均(x百万)',
        criteria_F_MARGIN: '纯益率 (%)',
        criteria_F_OP_MARGIN: '营业利润率 (%)',
        criteria_AEBITDMG: '折旧及摊销前获利率(%)',
        criteria_AGROSMGN: '毛利率(%)',
        criteria_APTMGNPCT: '税前利润',
        criteria_ASGA2REV: '支出销售净额比 (%)',
        criteria_ABVPS: '每股帐面价值',
        criteria_ATANBVPS: '每股有形资产价值',
        criteria_ACAPSPPS: '每股股本支出',
        criteria_ACSHPS: '每股现金',
        criteria_TTMEBITDPS: '每股EBITDA',
        criteria_AEPSNORM: '归一化每股收益',
        criteria_A1FCFSHR: '每股自由现金流',
        criteria_ALTDPS: '长期债务/股份',
        criteria_AREVPS: '收入/ 股份',
        criteria_F_ROE: '股本回报率 (%)',
        criteria_F_ROA: '资产回报率 (%)',
        criteria_AROIPCT: '投资回报率 (%)',
        criteria_ACURRATIO: '流动比率 (%)',
        criteria_AQUICKRATI: '速动比率 (%)',
        criteria_F_DIV_PAYOUT: '支付比率 (%)',
        criteria_F_TOT_ASSET_EQTY_RATIO: '股东资产比率 (%)',
        criteria_F_INT_COV_RATIO: '利息覆盖率',
        criteria_F_DEBT_ASSET_RATIO: '债务总额/总资产 (%)',
        criteria_ATOTD2AST: '总债务/总资本 (%)',
        criteria_ATOTD2EQ: '债务总额/总股本 (%)',
        criteria_AWCAPPSPR: '每股流动资金/价格',
        criteria_Reinvest_A: '再投资率 (%)',
        criteria_F_INV_REV_RATIO: '存货周转率',
        criteria_F_REC_REV_RATIO: '应收账款周转率',
        criteria_AASTTURN: '资产周转率',
        criteria_TrdCycle_A: '平均净贸易周期(天)',
        criteria_ANIPEREMP: '净收入/员工',
        criteria_AREVPEREMP: '收入/员工',
        criteria_F_REV_GROWTH_RATE: '收入增长率 (%)',
        criteria_F_DIV_YIELD_GROWTH_RATE: '股息收益率增长率 (%)',
        criteria_ATACHG: '总资产％变动',
        criteria_BVTRENDGR: '每增长率帐面价值 (%)',
        criteria_CSPTRENDGR: '资本支出增长率 (%)',
        criteria_CFTRENDGR: '现金流量增长率 (%)',
        criteria_GMNTRENDGR: '毛利率增长率 (%)',
        criteria_ANLOANCHG: '净贷款％变动',
        criteria_ANICHG: '净收入增长率 (%)',
        criteria_NPMTRENDGR: '净利润率增长率 (%)',
        criteria_T_SHORT_GOLDX: '短期黄金交叉点',
        criteria_T_MID_GOLDX: '中期黄金交叉点',
        criteria_T_SHORT_DEADX: '短期死亡交叉点',
        criteria_T_MID_DEADX: '中期死亡交叉点',
        criteria_T_3LINE_BREAK_BUY: '三线突破 (买入讯号)',
        criteria_T_3LINE_BREAK_SELL: '三线突破 (买出讯号))',
        criteria_T_BOLL_BULL: '突破布林通道 (牛市)',
        criteria_T_BOLL_BEAR: '突破布林通道 (熊市)',
        criteria_T_RSI: '最近14天的相对强弱指数',
        criteria_T_FAST_STO: '快速随机指标',
        criteria_T_SLOW_STO: '慢速随机指标',
        criteria_T_DMI: '动向指数',
        criteria_T_RCI: '排名相关指数',
        criteria_T_PSYCHO_LINE: '心理线',
        criteria_T_MACD_BULLX: '指数平滑异同移动平均线(看升信号)',
        criteria_T_MACD_BEARX: '指数平滑异同移动平均线(看跌信号)',
        criteria_BETA: 'Beta',
        criteria_DVOLSHSOUT: '成交交量(每日)占已发行股份%',
        criteria_MVOLSHSOUT: '成交交量(每月)占已发行股份%',
        criteria_PR26WKPCT: '价格 - 26星期价格%改变',
        criteria_PR52WKPCT: '价格 - 52星期价格%改变',
        criteria_PRYTDPCT: '价格 - 年至今%改变',
        criteria_VOL10DAVG: '成交量 - 最近10天平均交易量(1百万)',
        criteria_VOL3MAVG: '成交量 - 最近3个月平均交易量(1百万)',
        criteria_VOL1DAVG: '成交量 - 1天平均(1百万)',
        step1: '第一步: 选择策略 或 自订策略',
        predefined: '预设策略',
        savedstrategy: '已储存的策略',
        step2: '第二步: 选择 市场',
        HK: '香港',
        CN: '中国',
        US: '美国',
        TW: '台湾',
        'marketbox-count': ' 股票',
        step3: '第三步: 选择 行业分类(非必要)',
        sectorselect: '行业选择',
        all: '所有',
        confirm: '确认',
        cancel: '取消',
        'sectorbox-count': ' 股票',
        advfilter: '进阶筛选 (最多5个)',
        addcriteria: '+ 标准',
        savestrategy: '储存策略',
        resetstrategy: '重置标准',
        stockof: ' 项目 ',
        stocktotal: ' 股票',
        code: '股票编号',
        company: '股票名称',
        exchange: '交易所',
        last: '现价',
        change: '涨跌价',
        changepct: '涨跌幅',
        prev: '前',
        next: '后',
        result: '筛选结果',
        back: '返回',
        advcriteria: '进阶标准',
        min: '最小',
        max: '最大',
        'Prv.Year': '前年',
        '3YrsAgo': '3年前',
        '5YrsAgo': '5年前',
        'Prv.YearSameQuarter': '前年相同季度',
        '5BizDaysAgo': '5工作天前',
        '20BizDaysAgo': '20工作天前',
        '3MthsAgo': '3月前',
        '6MthsAgo': '6月前',
        '1YrAgo': '1年前',
        '10YrsAgo': '10年前',
        '9BizDaysAgo': '9工作天前',
        '26BizDaysAgo': '26工作天前',
        '13WksAgo': '13周前',
        '26WksAgo': '26周前',
        NXB: '美国 NASDAQ',
        NBA: '美国 AMEX',
        NBN: '美国 NYSE',
        NYQ: '美国 NYSE',
        ASQ: '美国 AMEX',
        NMQ: '美国 NASDAQ',
        NAQ: '美国 NASDAQ',
        PCQ: '美国 NYSE',
        NSQ: '美国 NASDAQ',
        OTC: '美国 PINK',
        PNK: '美国 PINK',
        OBB: '美国 OTC',
        HKG: '香港 HKEX',
        SHH: '中国 SSE',
        SHZ: '中国 SZSE',
        TAI: '台湾 TWSE',
        TWO: '台湾 TPEX',
        strategy0: '策略 1',
        strategy1: '策略 2',
        strategy2: '策略 3',
        strategy3: '策略 4',
        noresults: '没有结果',
        'duplicate-criteria': '该标准已被选取。请选择其他标准。',
        'no-sector': '请选择最少一行业',
    },
};
