// Resource - zh_TW
LabCI.WP.ScreenerPageObj.PAGEOBJ_RESOURCEBUNDLE.en = {
    lbl: {
        5130: 'Application Resources',
        5310: 'Auto & Auto Parts',
        5510: 'Banking & Investment Services',
        5110: 'Chemistry',
        5320: 'Consumer Durables',
        5330: 'Consumer Services',
        5620: 'Drug and Medical Research',
        5010: 'Energy',
        5410: 'Food & Beverage',
        5550: 'Fund',
        5610: 'Health Care Services',
        5560: 'Holding Company',
        5230: 'Industrial Conglomerate',
        5210: 'Industrial Goods',
        5220: 'Industrial Services',
        5530: 'Insurance',
        5120: 'Mineral Resource',
        5420: 'Personal & Household Gds & Serv',
        5540: 'Real Estate',
        5020: 'Renewable Energy',
        5340: 'Retail',
        5430: 'Retail- Food & Drug',
        5720: 'Software & IT Services',
        5710: 'Technology Equipment',
        5810: 'Telecommunication Services',
        5240: 'Transportation',
        5030: 'Uranium',
        5910: 'Utilities',
        criteriatype_valuation: 'Valuation',
        criteriatype_dividend: 'Dividend',
        criteriatype_share_related: 'Share Related Items',
        criteriatype_profitability_ratio: 'Profitability Ratios',
        criteriatype_pershare_ratio: 'Per Share Ratios',
        criteriatype_mgt_effectiveness: 'Management Effectiveness',
        criteriatype_financial_strength: 'Financial Strength',
        criteriatype_efficiency_ratio: 'Efficiency Ratios',
        criteriatype_growth_rate: 'Growth Rates',
        criteriatype_ta_trend: 'Technical Indicator (Trend)',
        criteriatype_ta_oscillator: 'Technical Indicator (Oscillator)',
        criteriatype_price_volume: 'Price and Volume',
        criteria_APENORM: 'P/E Normalized',
        criteria_F_PBR: 'Price To Book',
        criteria_APRCFPS: 'Price To Free Cash Flow per Share',
        criteria_APRICE2TOTEQ: 'Price To Equity',
        criteria_F_PSR: 'Price To Sales',
        criteria_F_DIV_YIELD: 'Dividend Yield',
        criteria_F_DIV: 'Dividend per Share',
        criteria_F_MKTCAP_USD: 'Market Cap (x1M Pricing Currency)',
        criteria_FLOATPRC_CUR: 'Float as a % of Total Shares O/S',
        criteria_SHSBOUTAVG: 'Shares outstanding Basic, average (x1M)',
        criteria_SHSOUT: 'Shares outstanding, current (x1M)',
        criteria_SHSOUTAVG: 'Shares outstanding, average (x1M)',
        criteria_F_MARGIN: 'Net Profit Margin (%)',
        criteria_F_OP_MARGIN: 'Operating Margin (%)',
        criteria_AEBITDMG: 'EBITD Margin (%)',
        criteria_AGROSMGN: 'Gross Margin (%)',
        criteria_APTMGNPCT: 'Pretax Margin',
        criteria_ASGA2REV: 'Expenses/Net Sales (%)',
        criteria_ABVPS: 'Book Value per Share',
        criteria_ATANBVPS: 'Tangible Book Value per Share',
        criteria_ACAPSPPS: 'Capital Spending per Share',
        criteria_ACSHPS: 'Cash per Share',
        criteria_TTMEBITDPS: 'EBITD per Share',
        criteria_AEPSNORM: 'EPS Normalised',
        criteria_A1FCFSHR: 'Free Cash Flow per Share',
        criteria_ALTDPS: 'Long Term Debt/Share',
        criteria_AREVPS: 'Revenue/Share',
        criteria_F_ROE: 'Return On Equity (ROE) (%)',
        criteria_F_ROA: 'Return On ssets (ROA) (%)',
        criteria_AROIPCT: 'Return On Investment (ROI) (%)',
        criteria_ACURRATIO: 'Current Ratio',
        criteria_AQUICKRATI: 'Quick Ratio',
        criteria_F_DIV_PAYOUT: 'Payout Ratio (%)',
        criteria_F_TOT_ASSET_EQTY_RATIO: 'Shareholder Equity Ratio (%)',
        criteria_F_INT_COV_RATIO: 'Interest Coverage',
        criteria_F_DEBT_ASSET_RATIO: 'Total Debt/Total Asset (%)',
        criteria_ATOTD2AST: 'Total Debt/Total Capital (%)',
        criteria_ATOTD2EQ: 'Total Debt/Total Equity (%)',
        criteria_AWCAPPSPR: 'Working Capital per Share/Price',
        criteria_Reinvest_A: 'Reinvestment Rate (%)',
        criteria_F_INV_REV_RATIO: 'Inventory Turnover',
        criteria_F_REC_REV_RATIO: 'Receivables Turnover',
        criteria_AASTTURN: 'Asset Turnover',
        criteria_TrdCycle_A: 'Average Net Trade Cycle (Days)',
        criteria_ANIPEREMP: 'Net Income/Employee',
        criteria_AREVPEREMP: 'Revenue/Employee',
        criteria_F_REV_GROWTH_RATE: 'Revenue Growth Rate (%)',
        criteria_F_DIV_YIELD_GROWTH_RATE: 'Dividend Yield Growth Rate (%)',
        criteria_ATACHG: 'Total Asset % Change',
        criteria_BVTRENDGR: 'Book Value Per Growth Rate (%)',
        criteria_CSPTRENDGR: 'Capital Spending Growth Rate (%)',
        criteria_CFTRENDGR: 'Cash Flow Growth Rate (%)',
        criteria_GMNTRENDGR: 'Gross Margin Growth Rate (%)',
        criteria_ANLOANCHG: 'Net Loans % Change',
        criteria_ANICHG: 'Net Income Growth Rate (%)',
        criteria_NPMTRENDGR: 'Net Profit Margin Growth Rate (%)',
        criteria_T_SHORT_GOLDX: 'Short-term Golden Cross',
        criteria_T_MID_GOLDX: 'Mid-term Golden Cross',
        criteria_T_SHORT_DEADX: 'Short-term Dead Cross',
        criteria_T_MID_DEADX: 'Mid-term Dead Cross',
        criteria_T_3LINE_BREAK_BUY: '3-line Break (Buy Signal)',
        criteria_T_3LINE_BREAK_SELL: '3-line Break (Sell Signal)',
        criteria_T_BOLL_BULL: 'Bollinger Breakout (Bullish Market)',
        criteria_T_BOLL_BEAR: 'Bollinger Breakout (Bearish Market)',
        criteria_T_RSI: 'Relative Strength Index (RSI) in last 14 days',
        criteria_T_FAST_STO: 'Fast Stochastic',
        criteria_T_SLOW_STO: 'Slow Stochastic',
        criteria_T_DMI: 'Directional Movement Indicator (DMI)',
        criteria_T_RCI: 'Rank Correlation Index (RCI)',
        criteria_T_PSYCHO_LINE: 'Psychological Line',
        criteria_T_MACD_BULLX: 'MACD (Bullish Signal)',
        criteria_T_MACD_BEARX: 'MACD (Bearish Signal)',
        criteria_BETA: 'Beta',
        criteria_DVOLSHSOUT: 'Volume (daily) as a % of Shares O/S',
        criteria_MVOLSHSOUT: 'Volume (monthly) as a % of Shares O/S',
        criteria_PR26WKPCT: 'Price - 26 week price % change',
        criteria_PR52WKPCT: 'Price - 52 week price % change',
        criteria_PRYTDPCT: 'Price - YTD price % change',
        criteria_VOL10DAVG: 'Volume - avg. trading vol. last 10 days (x1M)',
        criteria_VOL3MAVG: 'Volume - avg. trading vol. last 3 months (x1M)',
        criteria_VOL1DAVG: 'Volume - 1 Day Average (x1M)',
        step1: 'Step 1. Select or formulate your own strategy',
        predefined: 'Predefined Strategies',
        savedstrategy: 'Saved Strategies',
        step2: 'Step 2. Select Market',
        HK: 'Hong Kong',
        CN: 'China',
        US: 'United States',
        TW: 'Taiwan',
        'marketbox-count': ' stock(s)',
        step3: 'Step 3. Select business classification (optional)',
        sectorselect: 'Sector Selection',
        all: 'All',
        confirm: 'Confirm',
        cancel: 'Cancel',
        'sectorbox-count': ' stocks(s)',
        advfilter: 'Advanced Filter (Max. 5)',
        addcriteria: '+ Criteria',
        savestrategy: 'Save Strategy',
        resetstrategy: 'Reset Criteria',
        stockof: ' of ',
        stocktotal: ' stock(s)',
        code: 'Code',
        company: 'Company',
        exchange: 'Exchange',
        last: 'Last',
        change: 'Change',
        changepct: 'Change %',
        prev: 'Previous',
        next: 'Next',
        result: 'Result',
        back: 'Back to Filter',
        advcriteria: 'Advanced Criteria',
        min: 'Min',
        max: 'Max',
        'Prv.Year': 'Prv. Year',
        '3YrsAgo': '3 Yrs Ago',
        '5YrsAgo': '5 Yrs Ago',
        'Prv.YearSameQuarter': 'Prv. Year Same Quarter',
        '5BizDaysAgo': '5 Biz Days Ago',
        '20BizDaysAgo': '20 Biz Days Ago',
        '3MthsAgo': '3 Mths Ago',
        '6MthsAgo': '6 Mths Ago',
        '1YrAgo': '1 Yr Ago',
        '10YrsAgo': '10 Yrs Ago',
        '9BizDaysAgo': '9 Biz Days Ago',
        '26BizDaysAgo': '26 BizDays Ago',
        '13WksAgo': '13 Wks Ago',
        '26WksAgo': '26 Wks Ago',
        NXB: 'USA NASDAQ',
        NBA: 'USA AMEX',
        NBN: 'USA NYSE',
        NYQ: 'USA NYSE',
        ASQ: 'USA AMEX',
        NMQ: 'USA NASDAQ',
        NAQ: 'USA NASDAQ',
        PCQ: 'USA NYSE',
        NSQ: 'USA NASDAQ',
        OTC: 'USA PINK',
        PNK: 'USA PINK',
        OBB: 'USA OTC',
        HKG: 'HK HKEX',
        SHH: 'China SSE',
        SHZ: 'China SZSE',
        TAI: 'Taipei TWSE',
        TWO: 'Taipei TPEX',
        strategy0: 'Strategy 1',
        strategy1: 'Strategy 2',
        strategy2: 'Strategy 3',
        strategy3: 'Strategy 4',
        noresults: 'No Results',
        'duplicate-criteria': 'The criteria has been selected. Please select other criterias.',
        'no-sector': 'Please choose at least one sector',
    },
};
