
// Resource - zh_TW
LabCI.WP.ScreenerPageObj.PAGEOBJ_RESOURCEBUNDLE.zh_HK = {

    lbl: {
        "5130": "應用資源",
        "5310": "汽車零件",
        "5510": "銀行與投資服務",
        "5110": "化學品",
        "5320": "耐用消費品",
        "5330": "消費者服務",
        "5620": "藥物與醫學研究",
        "5010": "能源",
        "5410": "食品與飲料",
        "5550": "基金",
        "5610": "保健服務",
        "5560": "控股公司",
        "5230": "工業集團",
        "5210": "工業品牌",
        "5220": "工業服務",
        "5530": "保險",
        "5120": "礦產資源",
        "5420": "個人及家庭用品及服務",
        "5540": "房地產",
        "5020": "再生能源",
        "5340": "零售",
        "5430": "零售 - 食品藥物",
        "5720": "軟件及信息技術服務",
        "5710": "技術設備",
        "5810": "電信業務",
        "5240": "運輸",
        "5030": "鈾",
        "5910": "公用事業",
        "criteriatype_valuation": "估值",
        "criteriatype_dividend": "股息",
        "criteriatype_share_related": "股票相關項目",
        "criteriatype_profitability_ratio": "盈利能力比率",
        "criteriatype_pershare_ratio": "每股比率",
        "criteriatype_mgt_effectiveness": "管理效能",
        "criteriatype_financial_strength": "財務實力",
        "criteriatype_efficiency_ratio": "成效比",
        "criteriatype_growth_rate": "增長率",
        "criteriatype_ta_trend": "技術指標(趨勢)",
        "criteriatype_ta_oscillator": "技術性指標(震盪)",
        "criteriatype_price_volume": "價格和成交量",
        "criteria_APENORM": "市盈率規範化",
        "criteria_F_PBR": "市帳率",
        "criteria_APRCFPS": "股價自由現金流比",
        "criteria_APRICE2TOTEQ": "價格公平",
        "criteria_F_PSR": "售價",
        "criteria_F_DIV_YIELD": "股息收益率",
        "criteria_F_DIV": "每股股息",
        "criteria_F_MKTCAP_USD": "市值 (x百萬定價貨幣)",
        "criteria_FLOATPRC_CUR": "浮動佔已發行股份總數的百分比",
        "criteria_SHSBOUTAVG": "基本股, 平均(x百萬)",
        "criteria_SHSOUT": "流通股票, 現時(x百萬)",
        "criteria_SHSOUTAVG": "流通股票, 平均(x百萬)",
        "criteria_F_MARGIN": "純益率 (%)",
        "criteria_F_OP_MARGIN": "營業利潤率 (%)",
        "criteria_AEBITDMG": "折舊及攤銷前獲利率(%)",
        "criteria_AGROSMGN": "毛利率(%)",
        "criteria_APTMGNPCT": "稅前利潤",
        "criteria_ASGA2REV": "支出銷售淨額比 (%)",
        "criteria_ABVPS": "每股帳面價值",
        "criteria_ATANBVPS": "每股有形資產價值",
        "criteria_ACAPSPPS": "每股股本支出",
        "criteria_ACSHPS": "每股現金",
        "criteria_TTMEBITDPS": "每股EBITDA",
        "criteria_AEPSNORM": "歸一化每股收益",
        "criteria_A1FCFSHR": "每股自由現金流",
        "criteria_ALTDPS": "長期債務/股份",
        "criteria_AREVPS": "收入/ 股份",
        "criteria_F_ROE": "股本回報率 (%)",
        "criteria_F_ROA": "資產回報率 (%)",
        "criteria_AROIPCT": "投資回報率 (%)",
        "criteria_ACURRATIO": "流動比率 (%)",
        "criteria_AQUICKRATI": "速動比率 (%)",
        "criteria_F_DIV_PAYOUT": "支付比率 (%)",
        "criteria_F_TOT_ASSET_EQTY_RATIO": "股東資產比率 (%)",
        "criteria_F_INT_COV_RATIO": "利息覆蓋率",
        "criteria_F_DEBT_ASSET_RATIO": "債務總額/總資產 (%)",
        "criteria_ATOTD2AST": "總債務/總資本 (%)",
        "criteria_ATOTD2EQ": "債務總額/總股本 (%)",
        "criteria_AWCAPPSPR": "每股流動資金/價格",
        "criteria_Reinvest_A": "再投資率 (%)",
        "criteria_F_INV_REV_RATIO": "存貨周轉率",
        "criteria_F_REC_REV_RATIO": "應收賬款周轉率",
        "criteria_AASTTURN": "資產周轉率",
        "criteria_TrdCycle_A": "平均淨貿易週期(天)",
        "criteria_ANIPEREMP": "淨收入/員工",
        "criteria_AREVPEREMP": "收入/員工",
        "criteria_F_REV_GROWTH_RATE": "收入增長率 (%)",
        "criteria_F_DIV_YIELD_GROWTH_RATE": "股息收益率增長率 (%)",
        "criteria_ATACHG": "總資產％變動",
        "criteria_BVTRENDGR": "每增長率帳面價值 (%)",
        "criteria_CSPTRENDGR": "資本支出增長率 (%)",
        "criteria_CFTRENDGR": "現金流量增長率 (%)",
        "criteria_GMNTRENDGR": "毛利率增長率 (%)",
        "criteria_ANLOANCHG": "淨貸款％變動",
        "criteria_ANICHG": "淨收入增長率 (%)",
        "criteria_NPMTRENDGR": "淨利潤率增長率 (%)",
        "criteria_T_SHORT_GOLDX": "短期黃金交叉點",
        "criteria_T_MID_GOLDX": "中期黃金交叉點",
        "criteria_T_SHORT_DEADX": "短期死亡交叉點",
        "criteria_T_MID_DEADX": "中期死亡交叉點",
        "criteria_T_3LINE_BREAK_BUY": "三線突破 (買入訊號)",
        "criteria_T_3LINE_BREAK_SELL": "三線突破 (買出訊號))",
        "criteria_T_BOLL_BULL": "突破布林通道 (牛市)",
        "criteria_T_BOLL_BEAR": "突破布林通道 (熊市)",
        "criteria_T_RSI": "最近14天的相對強弱指數",
        "criteria_T_FAST_STO": "快速隨機指標",
        "criteria_T_SLOW_STO": "慢速隨機指標",
        "criteria_T_DMI": "動向指數",
        "criteria_T_RCI": "排名相關指數",
        "criteria_T_PSYCHO_LINE": "心理線",
        "criteria_T_MACD_BULLX": "指數平滑異同移動平均線(看升信號)",
        "criteria_T_MACD_BEARX": "指數平滑異同移動平均線(看跌信號)",
        "criteria_BETA": "Beta",
        "criteria_DVOLSHSOUT": "成交交量(每日)佔已發行股份%",
        "criteria_MVOLSHSOUT": "成交交量(每月)佔已發行股份%",
        "criteria_PR26WKPCT": "價格 - 26星期價格%改變",
        "criteria_PR52WKPCT": "價格 - 52星期價格%改變",
        "criteria_PRYTDPCT": "價格 - 年至今%改變",
        "criteria_VOL10DAVG": "成交量 - 最近10天平均交易量(1百萬)",
        "criteria_VOL3MAVG": "成交量 - 最近3個月平均交易量(1百萬)",
        "criteria_VOL1DAVG": "成交量 - 1天平均(1百萬)",
        "step1": "第一步: 選擇策略 或 自訂策略",
        "predefined": "預設策略",
        "savedstrategy": "已儲存的策略",
        "step2": "第二步: 選擇 市場",
        "HK": "香港",
        "CN": "中國",
        "US": "美國",
        "TW": "台灣",
        "marketbox-count": " 股票",
        "step3": "第三步: 選擇 行業分類(非必要)",
        "sectorselect": "行業選擇",
        "all": "所有",
        "confirm": "確認",
        "cancel": "取消",
        "sectorbox-count": " 股票",
        "advfilter": "進階篩選 (最多5個)",
        "addcriteria": "+ 標準",
        "savestrategy": "儲存策略",
        "resetstrategy": "重置標準",
        "stockof": " 項目 ",
        "stocktotal": " 股票",
        "code": "代碼",
        "company": "股票名稱",
        "exchange": "交易所",
        "last": "現價",
        "change": "漲跌價",
        "changepct": "漲跌幅",
        "prev": "前",
        "next": "後",
        "result": "篩選結果",
        "back": "返回",
        "advcriteria": "進階標準",
        "min": "最小",
        "max": "最大",
        "Prv.Year": "前年",
        "3YrsAgo": "3年前",
        "5YrsAgo": "5年前",
        "Prv.YearSameQuarter": "前年相同季度",
        "5BizDaysAgo": "5工作天前",
        "20BizDaysAgo": "20工作天前",
        "3MthsAgo": "3月前",
        "6MthsAgo": "6月前",
        "1YrAgo": "1年前",
        "10YrsAgo": "10年前",
        "9BizDaysAgo": "9工作天前",
        "26BizDaysAgo": "26工作天前",
        "13WksAgo": "13週前",
        "26WksAgo": "26週前",
        "NXB": "美國 NASDAQ",
        "NBA": "美國 AMEX",
        "NBN": "美國 NYSE",       
        "NYQ": "美國 NYSE",
        "ASQ": "美國 AMEX",
        "NMQ": "美國 NASDAQ",
        "NAQ": "美國 NASDAQ",
        "PCQ": "美國 NYSE",
        "NSQ": "美國 NASDAQ",
        "OTC": "美國 PINK",
        "PNK": "美國 PINK",
        "OBB": "美國 OTC",
        "HKG": "香港 HKEX",
        "SHH": "中國 SSE",
        "SHZ": "中國 SZSE",
        "TAI": "台灣 TWSE",
        "TWO": "台灣 TPEX",
        "strategy0": "策略 1",
        "strategy1": "策略 2",
        "strategy2": "策略 3",
        "strategy3": "策略 4",
        "noresults": "沒有結果",
        "duplicate-criteria": "該標準已被選取。請選擇其他標準。",
        "no-sector": "請選擇最少一行業"
    }

};