// Resource - zh_TW
LabCI.WP.WorldNavPageObj.PAGEOBJ_RESOURCEBUNDLE.zh_TW = {
    lbl: {
        turnoverlabel: '成交金額',
        intradaylabel: '日內圖',
        dailylabel: '日線圖',
        weeklylabel: '週線圖',
        monthlylabel: '月線圖',
        '1Mlabel': '1月',
        '3Mlabel': '3月',
        '6Mlabel': '6月',
        '1Ylabel': '1年',
        TWIIslabel: '加權指數',
        TWIIlabel: '台灣加權股價指數',
        SSECslabel: '上證指數',
        SSEClabel: '上証綜合指數',
        SZSCslabel: '深圳綜合',
        SZSClabel: '深圳综合股票指数',
        HSIslabel: '恒指',
        HSIlabel: '恒生指數',
        DJIslabel: '道瓊指數',
        DJIlabel: '道瓊斯工業平均指數',
        IXICslabel: '那斯達克',
        IXIClabel: '那斯達克指數',
        STIslabel: '星股海峽',
        STIlabel: '新加坡海峽時報指數',
        NIKKEIslabel: '日經指數',
        NIKKEIlabel: '日經平均指數',
        refreshlabel: '更新',
        clickdesclabel: '*點選指數獲取更多信息',
        unit: '  單位',
    },
};
