// Resource - zh_TW
LabCI.WP.WorldNavPageObj.PAGEOBJ_RESOURCEBUNDLE.en = {
    lbl: {
        turnoverlabel: 'Turnover',
        intradaylabel: 'Intraday',
        dailylabel: 'Daily',
        weeklylabel: 'Weekly',
        monthlylabel: 'Monthly',
        '1Mlabel': '1M',
        '3Mlabel': '3M',
        '6Mlabel': '6M',
        '1Ylabel': '1Y',
        TWIIslabel: 'TAIEX',
        TWIIlabel: 'TAIWAN SE WEIGHTED INDEX',
        SSECslabel: 'SSE COMP',
        SSEClabel: 'Shanghai SE Composite Index',
        SZSCslabel: 'SZSE COMP',
        SZSClabel: 'Shenzhen SE Composite Index',
        HSIslabel: 'HSI',
        HSIlabel: 'Hang Seng Index',
        DJIslabel: 'DOW JONES',
        DJIlabel: 'Dow Jones Index',
        IXICslabel: 'NASDAQ',
        IXIClabel: 'Nasdaq Composite Index',
        STIslabel: 'STI',
        STIlabel: 'Straits Times Index',
        NIKKEIslabel: 'NIKKEI',
        NIKKEIlabel: 'Nikkei 225',
        refreshlabel: 'Refresh',
        clickdesclabel: '*Click on index for more',
        unit: '  Unit',
    },
};
