export const RESIZE_EVENT = 'RESIZE_EVENT';
export const SHOW_LOGIN = 'SHOW_LOGIN';
export const SET_SERVER_NAV_ITEMS = 'SET_SERVER_NAV_ITEMS';
export const SET_CLIENT_NAV_ITEMS = 'SET_CLIENT_NAV_ITEMS';
export const SHOW_MENU = 'SHOW_MENU';
export const SHOW_MASK = 'SHOW_MASK';
export const SET_PERSONAL_AREA_VISIBLE = 'SET_PERSONAL_AREA_VISIBLE';
