export const RESIZE_EVENT = 'RESIZE_EVENT';
export const IS_LOGIN = 'IS_LOGIN';
export const SHOW_LOGIN = 'SHOW_LOGIN';
export const SET_ACCOUNTS = 'SET_ACCOUNTS';
export const SET_SERVER_NAV_ITEMS = 'SET_SERVER_NAV_ITEMS';
export const SET_CLIENT_NAV_ITEMS = 'SET_CLIENT_NAV_ITEMS';
